### ISSUE TITLE
Не работает подсветка синтаксиса

### ISSUE THREAD

**Issue by RickCastle2018** [Lereena/pascalabcnet-vs#1]
![image](https://user-images.githubusercontent.com/48931166/146231174-45c4fc5b-7119-4cb9-b9ac-ba8a44ed8a4e.png)

**Comment by Lereena** [comment]
Подскажите версию Code OSS и плагина

**Comment by RickCastle2018** [comment]
pascalabcnet `v1.1.5`
Released on
5/25/2021, 24:41:18
Last updated
11/28/2021, 22:49:45
Identifier
lereenadem.pascalabcnet

```
> code --version                                                                                                                                                                   ✔ 
1.62.0
b3318bc0524af3d74034b8bb8a64df0ccf35549a
x64
```

**Comment by RickCastle2018** [comment]
Устанавливал ПаскальАБЦ из Manjaro AUR (http://aur.archlinux.org/packages/pascalabcnet)
![image](https://user-images.githubusercontent.com/48931166/146234404-8eec4e2b-eb43-4e60-919d-db9a7af801ef.png)

**Comment by RickCastle2018** [comment]
@Lereena, возможно, старый компилятор? (Хотя нет, вроде новая версия -- 3.8.2)

**Comment by Lereena** [comment]
Спасибо
Правильно понимаю что компиляция и запуск работают нормально, а подсветки нет на любой программе?

**Comment by RickCastle2018** [comment]
@Lereena Да, так и есть

**Comment by RickCastle2018** [comment]
Всегда рад помочь открытому коду!

**Comment by RickCastle2018** [comment]
@Lereena сейчас проверил, autocomplete вроде работает тоже. Действительно, нет только подсветки

**Comment by RickCastle2018** [comment]
@Lereena Это временный фикс, вижу, что есть tree-sitter-pascalabc. Но, почему-то, не работает :(

**Comment by Lereena** [comment]
Пока что не получается воспроизвести эту проблему
Вы устанавливали расширение из Open VSX, или может быть добавляли поддержку Visual Studio Marketplace и качали оттуда?
Скажите ещё версию ядра Linux на которой основана ваша Manjaro, я попробую на ней (было бы очень странно если бы проблема была как-то связана с этим, но вдруг)

**Comment by RickCastle2018** [comment]
Добавлял поддержку официального маркетплейса от Microsoft

**Comment by Spyke09** [comment]
Та же самая проблема, не работает подсветка и autocomplete, а с компиляцией все в порядке.

**Comment by RickCastle2018** [comment]
@Spyke09 А какая операционная система? @Lereena, к слову, почему-то есть открытый ишью у VSCode по поводу tree-sitter - https://github.com/microsoft/vscode/issues/50140

**Comment by Spyke09** [comment]
@RickCastle2018  Windows 10

**Comment by SeryiBaran** [comment]
Такая же проблема, только ещё ошибками сыплет:

![image](https://github.com/miks1965/pascalabcnet-vs/assets/82605415/a1aeb574-3db8-43c2-bb29-b08df44875eb)


```
node:internal/deps/undici/undici:11576
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:6893:35)
      at schemeFetch (node:internal/deps/undici/undici:11036:18)
      at node:internal/deps/undici/undici:10909:26
      at mainFetch (node:internal/deps/undici/undici:10926:11)
      at fetching (node:internal/deps/undici/undici:10883:7)
      at fetch2 (node:internal/deps/undici/undici:10761:20)
      at Object.fetch (node:internal/deps/undici/undici:11574:18)
      at fetch (node:internal/process/pre_execution:243:25)
      at c:\Users\ivan\.vscode\extensions\lereenadem.pascalabcnet-1.1.5\node_modules\web-tree-sitter\tree-sitter.js:1:15041
      at c:\Users\ivan\.vscode\extensions\lereenadem.pascalabcnet-1.1.5\node_modules\web-tree-sitter\tree-sitter.js:1:15262
}

Node.js v18.17.1
[Info  - 9:05:07 PM] Connection to server got closed. Server will restart.
```

При этом компилирует и запускает нормально:

![image](https://github.com/miks1965/pascalabcnet-vs/assets/82605415/8ba7bd32-65e3-43f4-a595-7c7b37f2cc04)

|||
| --- | --- |
| Операционная система | Windows 10 Pro 1909 |
| Версия компилятора (лежит в папке с PascalABC.NET) | PascalABCCompiler.Core v3.9.0.3417 |
